#!/usr/bin/env python3
"""Build knowledge/INDEX.json and knowledge/INDEX.md from doc frontmatter.

Run from repo root:  python3 scripts/build-index.py
The index is the machine-readable entrypoint agents use to locate docs.
"""
import os, json

from frontmatter import parse_text, schema_errors

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KB = os.path.join(ROOT, "knowledge")

topics = {}
for topic in sorted(os.listdir(KB)):
    tdir = os.path.join(KB, topic)
    if not os.path.isdir(tdir):
        continue
    docs = []
    for fn in sorted(os.listdir(tdir)):
        if not fn.endswith(".md"):
            continue
        path = os.path.join(tdir, fn)
        with open(path, encoding="utf-8") as f:
            meta, _ = parse_text(f.read(), path)
        meta = meta or {}
        errors = schema_errors(meta)
        if errors:
            raise SystemExit(f"{path}: " + "; ".join(errors))
        rel = os.path.relpath(path, ROOT)
        try:
            order = int(meta.get("order", 999))
        except (TypeError, ValueError):
            order = 999
        docs.append({
            "id": meta.get("id", f"{topic}/{fn[:-3]}"),
            # AGENTS.md tells agents to match on `topic` and to follow `related`.
            # Both must be on the document itself: an agent working from the index
            # cannot infer the first from a dict key or find the second at all.
            "topic": meta.get("topic", topic),
            "title": meta.get("title", fn[:-3]),
            "slug": meta.get("slug", ""),
            "type": meta.get("type", "doc"),
            "order": order,
            "status": meta.get("status", "unknown"),
            "maturity": meta.get("maturity", "unverified"),
            "tags": meta.get("tags", []),
            # Present only when they say something: the variant a doc is specific
            # to, and the doc that owns the rule when two topics cover one subject.
            **({"applies_to": meta["applies_to"]} if meta.get("applies_to") else {}),
            **({"defers_to": meta["defers_to"]} if meta.get("defers_to") else {}),
            "verified_against": meta.get("verified_against", ""),
            "source_urls": meta.get("source_urls", []),
            "last_reviewed": meta.get("last_reviewed", ""),
            "review_after": meta.get("review_after", ""),
            "related": meta.get("related", []),
            "when_to_use": meta.get("when_to_use", ""),
            "path": rel,
        })
    docs.sort(key=lambda d: (d["order"], d["id"]))
    ready = sum(1 for d in docs if d["status"] == "ready")
    topics[topic] = {
        "path": f"knowledge/{topic}",
        "doc_count": len(docs),
        "ready": ready,
        "draft": len(docs) - ready,
        "docs": docs,
    }

total = sum(t["doc_count"] for t in topics.values())
ready_total = sum(t["ready"] for t in topics.values())
maturities = {}
for topic in topics.values():
    for doc in topic["docs"]:
        maturities[doc["maturity"]] = maturities.get(doc["maturity"], 0) + 1
index = {
    "schema": "ai-engineering-kit/knowledge-index@1",
    "note": "Regenerate with `python3 scripts/build-index.py`. Do not edit by hand.",
    "stats": {"topics": len(topics), "docs": total, "ready": ready_total,
              "draft": total - ready_total, "maturity": maturities},
    "topics": topics,
}

with open(os.path.join(KB, "INDEX.json"), "w", encoding="utf-8") as f:
    json.dump(index, f, indent=2, ensure_ascii=False)
    f.write("\n")

# A regeneration that finds nothing is a broken invocation, not an empty base —
# wrong working directory, a moved tree. Writing the result would replace a good
# index with an empty one, so refuse instead.
if total == 0:
    raise SystemExit(
        "error: no documents found under knowledge/. Run from the repository root."
    )

# Human-readable INDEX.md
lines = ["# Knowledge Index", "",
         "> Auto-generated by `scripts/build-index.py`. Do not edit by hand.",
         "> Machine-readable version: [`INDEX.json`](./INDEX.json).", "",
         f"**{len(topics)} topics · {total} docs · {ready_total} ready · {total - ready_total} draft**", "",
         "Agents: load `INDEX.json`, filter `status: \"ready\"`, match `tags` / `when_to_use`, then read `path`.", ""]
for topic in sorted(topics):
    t = topics[topic]
    lines.append(f"## {topic}  ({t['ready']}/{t['doc_count']} ready)")
    lines.append("")
    lines.append("| # | Title | Status | Path |")
    lines.append("|---|-------|--------|------|")
    for d in t["docs"]:
        num = "" if d["order"] < 0 else d["order"]
        mark = "✅" if d["status"] == "ready" else "⬜"
        lines.append(f"| {num} | {d['title']} | {mark} {d['status']} | `{d['path']}` |")
    lines.append("")
with open(os.path.join(KB, "INDEX.md"), "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"INDEX.json + INDEX.md written: {len(topics)} topics, {total} docs, {ready_total} ready")
